const BLACK_COLOR = '#313339'
const WHITE_COLOR = '#FFF'
const GRAY_COLOR = '#C6C7CB'
const GRAY_DARK_COLOR = '#53565F'
const GRAY_LIGHT_COLOR = '#E2E4E7'
const RED_COLOR = '#E01B0E'
const ORANGE_COLOR = '#F26A24'
const BLUE_COLOR = '#008cce'


const Colors = { WHITE_COLOR, BLACK_COLOR, GRAY_COLOR, GRAY_LIGHT_COLOR, GRAY_DARK_COLOR, RED_COLOR, ORANGE_COLOR, BLUE_COLOR }

export default Colors